name: Scrape Webpage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraping script
        run: |
          python scrape_webpage.py

      - name: Commit scraped content
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git pull origin main  # Fügen Sie diesen Schritt hinzu, um die Änderungen zu pullen
          git add training_data.json
          git commit -m 'Update scraped webpage content'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.LMM_TOKEN }}
