name: Scrape Webpage

on:
  workflow_dispatch:  # Ermöglicht manuelles Triggern des Workflows
  push:
    paths:
      - 'scrape_webpage.py'  # Nur ausführen, wenn das Scraping-Skript geändert wird

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraping script
        run: |
          python scrape_webpage.py

      - name: Commit and push scraped content
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add webpage_content.txt
          git commit -m 'Update scraped webpage content'
          git pull --rebase origin main  # Änderungen vom Remote-Repository ziehen und integrieren
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
