name: Train Model

on:
  push:
    paths:
      - 'training_data.json'  # Nur auslösen, wenn sich training_data.json ändert
  workflow_dispatch:  # Manuelles Triggern ermöglichen

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Set up Git LFS
        run: git lfs install

      - name: Checkout LFS files
        run: git lfs pull

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training script
        run: python train_model.py

      - name: Upload model to repository
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git lfs install
          git pull origin main  # Pull Änderungen vor dem Push
          git add trained_model/pytorch_model.bin
          git add trained_model/config.json
          git add trained_model/tokenizer_config.json
          git add trained_model/vocab.json  # Falls vorhanden
          git add trained_model/merges.txt  # Falls vorhanden
          git commit -m 'Add trained model'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.LMM_Token }}
